remote_theme: "mmistakes/minimal-mistakes@4.14.1"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

include: ["_pages"]
  
minimal_mistakes_skin: "plum"

locale: "pl-PL"

title: "-10te urodziny"

paginate: 5

name: ""

search: false

footer:

comments:
  provider: "facebook"
  facebook:
    appid:
    num_posts: 5
    colorscheme: "dark"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      comments: true
      read_time: false
      author_profile: true
      related: false
      toc: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      toc: true

markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

author:
  name             : "Bart&Seba&Pioter"
  avatar           : "/assets/-10_post.jpg"
  bio              : "-10te urodziny blog"
  location         : ""
  email            : minus10urodziny@gmail.com
  links:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://facebook.com/"
